### PR TITLE
Seperator

### PR DESCRIPTION
**Pull request by Vytautas-Hermann**

### CODE REVIEW

**Review by jmeintrup — COMMENTED** [review]
Use the .clang-format config to format all files please

**Comment by Vytautas-Hermann** [comment]
Thanks for the reply. I've installed clang-format and run it on all files I changed/created.

**Review by jmeintrup — CHANGES_REQUESTED** [review]
Please rename all occurences of _sep**e**rator_ with the correct spelling _sep**a**rator_

**Review by andrej-sajenko — DISMISSED** [review]

**Comment by andrej-sajenko** [comment]
@1yay1 Should be done. Hope I did not forget anything.

**Review by jmeintrup — APPROVED** [review]

**Pull request merged**
