### PR TITLE
Breadth-first search

### PR DESCRIPTION
**Pull request by shsr04**
This solves the BFS problem for a graph G=(V,E).
- Time: O(n+m)
- Space: O(n) bits

### CODE REVIEW

**Comment by shsr04** [comment]
Did I break something?

**Review by dppl — COMMENTED** [review]
Will look further into it.

**Comment by andrej-sajenko** [comment]
Hi @shsr04, can you tell me why you disabled the tests in this pull request? 
Recall your last commit message: 'disable CD iterator test for now'

**Comment by shsr04** [comment]
The test is failing for unknown reasons (see #31). @dappels can not reproduce the error, so I think the test is not useful.

**Comment by dppl** [comment]
As @shsr04 said I was not able to reproduce the error locally with the current master version.
However even after cloning his branch and running the test I'm still not able to reproduce the problem.

The error also does not seem to be related to the fixed seed, which is used to shuffle the test set in order to fill the words in an unordered way.

Could the error be somehow related to different clang versions?

**Comment by shsr04** [comment]
I have tried with `g++ 6.3.0` and `clang++ 3.8`, both give the same error.

**Pull request merged**
