### PR TITLE
GML import/export

### PR DESCRIPTION
**Pull request by shsr04**
Now you can export a graph to a .gml file and import a graph from one. (Good for viewing and editing graphs with a tool like Gephi)

### CODE REVIEW

**Review by andrej-sajenko — CHANGES_REQUESTED** [review]
Thank you. Can you add some doc comments please.

**Review by andrej-sajenko — APPROVED** [review]

**Comment by edward1958** [comment]
Hi! I have text network output files in xml and would like to import them into Gephi to generate graphs and statistics. Can I convert the xml file to gexf or is there another preferred method? Any guidance is appreciated. Thanks a bunch! Ed

**Comment by shsr04** [comment]
@edward1958 If you have a custom XML format, you probably have to transform it manually into a format readable by Gephi (https://gephi.org/users/supported-graph-formats/). Maybe someone at https://github.com/gephi/gephi can help you further.

**Comment by edward1958** [comment]
Hi! Thank you for your reply.  I very well may have to take that route. Thanks again and have a nice weekend!

**Pull request merged**
